### ISSUE TITLE
Starting music at startup very slow. 

### ISSUE THREAD

**Issue by donsaimon** [BimmerGestalt/AAIdrive#336]
When I power on the car, I have to wait about 2 minutes before AAI connects and music play starts. This happens if I left the car for relatively long times (e.g. 2 hours), while if I power off the car and I power on again in a few minutes, the whole process is much more fast.
Suggestions to make the process faster also at the first startup after hours?

**Comment by hufman** [comment]
My original goal of the entire project was entirely just to bring the music apps to the car :) I assure you that I would improve the connection speed further if I could.
Have you tried disabling battery optimizations or enabling background execution on the BMW app?

**Comment by donsaimon** [comment]
Thanks for the answer. Yes I have background ops enabled and battery optimizations disabled.
Maybe automatic opening of BMW app at the car startup helps? 
I do not understand why if I power on the car after some hours the system is slower to connect, while I power on the car after a few minutes the system is a lot faster...

**Comment by JoeDoe2021** [comment]
I can also report some lagginess, but I've been living with that (some lagginess but app working = better than no app).

But I do confirm, oddly there are moments when "things take time". App does not actually disconnect, but nothing sounds, just gets stuck there. Or shows playing, but no audio. It's like the audio connection hangs momentarily. Like, for example, pausing (pressing "ON" radio button and muting / pausing), then trying to resume. Or changing sources. Even if sometimes I am forced to change to radio, then back to App, so that sound restarts. Just odd behavior. But again, I'd rather blame this on the way Android manages audio and connections, really.

If I can, I'll try to further detail my occurrences.

Cheers !

**Comment by donsaimon** [comment]
Yes, sometimes it happens to me too, specially when I pass from Simple Radio to Spotify inside AAI app. Spotify audio is sometime mute, so I have to temporarily change audio source (I go to my USB key) and then come back to AAI.
What version are you using? I am on c87b487

**Comment by JoeDoe2021** [comment]
Hi - my reported behaviour already applied to version 1.2.2 and persists in 1.3 RC.
I will start testing Nightly builds as soon as I can.
I'm afraid though that I cannot refer to the Nightly version properly.
Is there a "nightly builds" repository with some sort of versioning?
Thanks!

**Comment by hufman** [comment]
@donsaimon I think you are experiencing the finicky nature of the BMW app, sometimes it connects smoothly and sometimes it takes a second time, and I'm working in #322 to try to work around that reconnection process.

@JoeDoe2021 I believe you might be experiencing a peculiar situation: I understand you have an ID4 system with USB support, Do you have Audio Context working? Does the Media button in your car open the Audioplayer or does it open the car's native Bluetooth interface? If the latter, then the car's native pause support goes through Bluetooth directly instead of through AAI, which adds a confounding layer. Selecting the Audioplayer button is meant to always trigger playback start, does that part work at least? AAI acts more as a general viewer, and doesn't receive any of the audio interactions from the car in this case (such as that pause button, or the skip back/next hardware buttons), so the available control is restricted. I hope this help explains some of the behavior you're seeing!

As for versioning, the [Commit History](https://github.com/hufman/AndroidAutoIdrive/commits/master) has a checkmark next to each commit which opens up the CI Build System, and builds from each commit are available for the last week. Within the app interface, the Support tab shows what commit your version was built from, which can be looked up in Commit History to see what changes have happened recently or since then.

**Comment by hufman** [comment]
As part of cfcabdd I deferred several UI initialization steps, which seems to enable the music to start playing sooner in my experience.
