### ISSUE TITLE
Cover art Spotify

### ISSUE THREAD

**Issue by ilross02** [BimmerGestalt/AAIdrive#364]
The Album cover picture in Spotify is not correctly displayed: when skipping a song or selecting a different one using directly the phone the album cover picture is the one from the first song that has been played. This doesn't happen when skipping/browsing songs using the iDrive (here the cover is correctly updated).

**Comment by hufman** [comment]
Hmmm I don't experience this. Can you explain more about your situation?

- What version of Spotify are you running?
- What version of AAI are you running?
- Did you grant access to Browse Your Spotify Library?

This Browse Your Spotify Library permission enables the protocol which allows for fetching the coverart directly from Spotify. Otherwise it relies on the ability to Control Active Music Apps, and Spotify's coverart in this mode is less reliable and sometimes doesn't show anything. It seems to only provide coverart if it is already cached, and so it successfully shows coverart if you play multiple songs from the same album or skip to a previous song you recently played.
I haven't heard of any situation where it would display the wrong coverart, it would either display the correct coverart or the placeholder image.

**Comment by xaviugs** [comment]
What version of Spotify are you running?
8.6.12.986
What version of AAI are you running?

the latest on 28 jul

Did you grant access to Browse Your Spotify Library?

I cannot grant acces.  The AAI says could not find spotify app    and    spotify web api authorized. 

THnks a alot

**Comment by hufman** [comment]
Very curious! Are you running a modded version of Spotify? AAIdrive doesn't care, and it shows those permission checkboxes if it sees any Spotify installed at all. The Spotify App SDK is the code that is complaining that it can't find the Spotify app, and it is unable to connect to modded Spotify apps.

**Comment by hufman** [comment]
Are you still experiencing this?

**Comment by ilross02** [comment]
No more, there were some problem related to the modded version: solved by subscribing to Premium xD. Thank you so much for the support, and congratulations for this beautiful project!

**Comment by hufman** [comment]
Glad to hear it! Thank you for the kind words!
