### ISSUE TITLE
Tidal integration 

### ISSUE THREAD

**Issue by Guskam** [BimmerGestalt/AAIdrive#415]
First I must praise the work you are doing! Very professional. I love your commitment and energy in this topic.
Since me and my family are using Tidal due to the higher bit rate and sound quality I'm sad to experience the lack of integration of the Tidal app. Or maybe I'm just not understanding how to do it right. I can't search, find my albums or playlist in the tidal app. The result is similar as a 
![Screenshot_20210925-224517](https://user-images.githubusercontent.com/91387837/134785590-217f3a5f-12f4-4813-a6af-1826e0aaa2a6.jpg)
Bluetooth audio connection plus the artwork. Is there any solution for this or a planned release in getting the same features as you have built for the Spotify app.
Br
Gustav

**Comment by hufman** [comment]
Thank you for the kind words! I'm so happy you like it!
I'm disappointed to see that Tidal has changed their support for allowing other apps to control their app since the last time I checked it.
I decompiled Tidal 2.46.0 and it looks like it will allow access to apps that have Notification Access. I see that you've now granted that permission (which might not have been in place during the original app scan), perhaps try pulling down on the list to rescan and hopefully that should enable control.
In my test just now, it didn't provide any contents in the Browse view even with control, but that may have been because I don't have a subscription. It's interesting that it gave Android Auto some contents, but I wasn't able to follow the dynamic code closely enough to figure out why.
But! Hopefully rescanning for music apps after granting Notification Access should enable full browsing for you, since you have a subscription.

It doesn't look like Tidal doesn't provide an App Control API like Spotify does, so there isn't much more that AAIdrive can do to enable support. Please reach out to Tidal customer service to inquire about adding support: Because it's a subscription service, they don't rely on ad revenue from within the app, and so they should be amenable to allowing other phone apps to control the music.

**Comment by Guskam** [comment]
Thanks for the fast reply.
When I update the list of music apps the "looking glass" appears but not the "folder". When I search and browse nothing appears though. See pics. Nothing you can do about it I guess. I have another app called bluesound that is controlling tidal but then I log in directly to the tidal site without passing through the tidal app. Tidal connect exist as well but it doesn't help us here. Thanks anyway! 
![Screenshot_20210926-085933](https://user-images.githubusercontent.com/91387837/134797452-539ccedd-829f-4b80-83fd-00bf36c7a64a.jpg)
![Screenshot_20210926-090003](https://user-images.githubusercontent.com/91387837/134797453-9a6653c4-7ccc-483d-a31f-c6d19d60869e.jpg)

**Comment by Guskam** [comment]
I tried to use "usb audio player pro" where I log onto the tidal account but it doesn't seem to work either. 
![Screenshot_20210926-095109](https://user-images.githubusercontent.com/91387837/134799008-9b04e8f6-4876-43fb-a42d-fe030e6204f8.jpg)

**Comment by hufman** [comment]
Indeed, as you say, there isn't much to be done :( Having the filled in circle around the play icon does mean it can launch the app, at least, which is definitely helpful. The search icon can be provided if a test search returns results (which it doesn't seem to in this case) or if it provides a Play From Search functionality (currently only testable from the car), which may still prove useful for you.

Please reach out to Tidal to request that they allow their MediaBrowserService to be browsed from other applications, since they seem amenable to enabling other app integrations for their Tidal Connect ecosystem.
Thank you again for your feedback and support!

**Comment by Guskam** [comment]
Just for your info. I got an answer from Tidal today without any hopes for the future... "Unfortunately, customer service does not have access to information regarding if or when certain features will be released and at this time TIDAL does not share it's API."
