### ISSUE TITLE
Spotify connects but cant be "opened"

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#463]
Hi,

I often have the issue, that spotify is connected, but cant be controled.
When entering the multi media menu, you see that spotify is detected and connected.
But as you click on that entry, nothing happens.
I can select tracks via my HUD, but I cant see Media Screen on the main screen ?

Have you seen this before

This is what it looks like, but I cant open this menu item.
When clicking on it, nothing happens.

![photo_2021-11-17_00-31-39](https://user-images.githubusercontent.com/10863304/142082772-7b58015b-427b-4356-a830-533057b2ad22.jpg)

**Comment by LACNR** [comment]
On each first connection you need to select the app you wanna use and then select the AudioPlayer entry which will move to the display, after that you can always directly select the app of choice.

**Comment by hufman** [comment]
Do you have other music apps installed on your phone, that you would normally expect to see in that menu? I've seen a similar problem on Huawei phones where the phone will pause the app because it's in the background, and if you open up the phone interface then the initialization will continue and the car apps will begin responding.
As a further test of whether the entire app is paused, is the Notifications app similarly stuck at the same time?

**Comment by Vasmares** [comment]
@LACNR  I dont quite get what you mean

@hufman Yes. I would also expect Youtube and Audible to be visable in the App list, but they arent.
Also when unlocking the phone and starting spotify, is does not get "controllable" in the car.
As of today, no apps appear at all :/

What do you mean by "notification app" ?

Build 1.3.1-8-eaab847 10.11.2021 16:31:29

**Comment by hufman** [comment]
Some phone OSs will pause AAIdrive if AAIdrive is not running in the foreground, and apparently the foreground notification is not enough. Does the app initialization continue to create the Audible (while running) and Youtube apps in the car when you open the AAIdrive phone interface? Opening the underlying music app won't change this, it's AAIdrive or it's connection to the car that is getting stuck.

If you enable the Notifications tab (notification permissions are not needed for this test), you should see a new book icon in the car's Connected menu and Messaging menu. This icon, just like the Spotify icon, requires that the phone app reply to the car when you click it so that the car knows what screen to show next, and so it should behave the same way if Android is indeed pausing the app.

**Comment by Vasmares** [comment]
I installed todays nightly build and all seems fixed.
Build 1.3.1-18-bde9fd1 23.11.2021 23:27:26

I have more options in the connected drive menu again.
Spotify starts quick and is fully controllable

What did you do  :D

**Comment by hufman** [comment]
Hmmm I'm not sure which [change between those commits](https://github.com/BimmerGestalt/AAIdrive/compare/eaab847..bde9fd1) would be the relevant one! I refactored the modules to be separate services, which might perhaps change some heuristics in the OS? I also slightly changed the behavior when detaching from a connected car which might keep the MainService as a Foreground Service for the next time you connect, but I haven't noticed much of a difference personally.
Hopefully it stays fixed for you!
