### ISSUE TITLE
Compiled version with google etc but some icons/text missing on menu?

### ISSUE THREAD

**Issue by scottjjr** [BimmerGestalt/AAIdrive#473]
Hi, first off great tool! Am loving the features available so far :)

Have complied a version with google api key etc and that all seems to work, however when selecting in the apps menu I have to guess which one it is as anything under the 'Google' icon/word either have icons only and no text, or no icon and no text, but the menu item exists and is selectable.  One of the icons is repeated  (looks like the old smartthings logo) for the maps version.

Is this a language issue? I have it set to english UK in a japanese import to New Zealand in a 2016 3 series with NBT EVO ID4

Thanks!

**Comment by hufman** [comment]
Thank you so much for the compliment!
The problem is that the BMW resources to log in to the car are cryptographically tied to the icon and text packs, and so by using the Samsung Smartthings app to log in to the car, it creates a Smartthings icon in the car. I opted to not send the matching text pack for the custom Maps app, which is why the label is missing for that icon; otherwise it would have a label saying SmartThings.
The empty Notifications app icon is different; it just doesn't have a matching text pack at all in the original BMW Connected resources.
As part of finishing up the custom map implementation, I'll be adding a better icon similar to the Notifications icon underneath the Office menu and similar to most of the music apps. I'm not sure how reliable ID4 is at switching to the main app after selecting those placeholder icons, however.

**Comment by scottjjr** [comment]
Ok many thanks for the explanation.

How is the custom maps implementation tracking? Anything we'll be seeing soon? :)

**Comment by hufman** [comment]
I daresay it could probably be done within half a year, but hopefully you won't hold me to that :)
