### ISSUE TITLE
incorrect handling of the "Media" button

### ISSUE THREAD

**Issue by unlive74** [BimmerGestalt/AAIdrive#500]
Hey Walter!
Haven't updated the aaid app for a long time, maybe more than a month. Build 9cf7c03 handles pressing "Media" strangely. The best way to show this is in a video: https://user-images.githubusercontent.com/75434533/149274093-8def3416-ec45-40ae-8187-f67027625084.mp4

**Comment by hufman** [comment]
I sincerely appreciate your patience in testing the latest build of the app and reporting any bugs you find!
Can you explain what you think is behaving strangely? Your video (very helpful!) shows how I expect and experience it.
Do you mean the lag in the menu before it finishes opening the app? I believe this is because when the car asks the app which screen to open first, the app might be busy with other things.
Each app module enforces single-threaded access to its car connection. While one thread (usually, the redraw thread that updates the song position every second) is busy talking to the car, any other commands have to wait (for example, [telling the car](https://github.com/BimmerGestalt/AAIdrive/blob/9cf7c03021324929e744bd45ebaac20e4bfc9c1e/app/src/main/java/me/hufman/androidautoidrive/carapp/music/MusicApp.kt#L325-L329) what screen to go to next). Even though AAIdrive has an optimization to not actually send the data to the car if the data hasn't changed, it still needs to wait for the other thread to finish before checking if the data is actually correct. The other step that happens during this button press that might need to wait is that it [tells the car](https://github.com/BimmerGestalt/AAIdrive/blob/9cf7c03021324929e744bd45ebaac20e4bfc9c1e/app/src/main/java/me/hufman/androidautoidrive/carapp/music/AVContextHandler.kt#L56) that the app is currently playing music, not paused or stopped. Only after these steps are complete will the car complete its transition to the music screen, and if it takes too long that car might just give up and stay in the Media menu. This last part, of staying in the Media menu, is the one that sometimes annoys me.
I will try to find some optimizations for this!

But, this behavior has been in place for a while. Was there a different misbehavior that you noticed starting recently?

**Comment by unlive74** [comment]
In my video, at the third second I press "Media", a menu appears with a list of applications (there are several applications besides Spotify, but I don't have time to select anything), which closes itself after a second (I don't select anything in it, it just closes), moreover, the display is no longer a general image, but an open Spotify application. If I press "Media" again (ninth second), a small window appears, but it only has the Spotify app, so I can't select, for example, Simple radio. It seems to me that the window with applications should not close itself at the fourth second, at least.

**Comment by hufman** [comment]
Ah ha, thank you for explaining!
The behavior of passing through the Media menu directly into the app is intended. For example, if you were listening to car's normal FM Radio or USB Storage apps, pushing the Media button will directly go to those apps. I think the menu lag is causing the impression that the Media menu is meant to be accessible. You would need to click the home screen's Media tile to access the list of media apps, or tilt the controller left twice as you do at 0:29.
As an additional method, you can use the Apps toolbar button (highlighted at 0:16) within the AAIdrive playback window, and this will allow you to switch apps without going out to the main Media menu.
