### ISSUE TITLE
Keine Verbindung zur Spotify App

### ISSUE THREAD

**Issue by 12hp** [BimmerGestalt/AAIdrive#505]
Nach 2-3 erfolgreichen Verbindungen kann ich Spotify nicht mehr über ID6 starten. Muß dann die aaidrive App neu installieren.

**Comment by hufman** [comment]
Thank you for reaching out! Let's check a few things:

- Does the car's Mobile Devices menu show the phone as connected for Apps, or just music?
- What happens when you open the AAIdrive app? It should try triggering MyBMW to connect to the car if it hasn't, or it should connect to the car if the Apps connection is ready.
- Have you adjusted the battery optimizations for MyBMW or AAIdrive? Your phone may think the app isn't being used and won't start the app in the background. What phone are you using?

**Comment by 12hp** [comment]
Es funktioniert jetzt gut. Spotify ist stabil wenn ich wenig Interaktion mache. Mein Telefon ist ein Exote. ULEFON Amor 9.
