### ISSUE TITLE
New Release delete Messages

### ISSUE THREAD

**Issue by Maexvie** [BimmerGestalt/AAIdrive#514]
Since last release incoming messages appear for 3sec. before they disapear.

**Comment by Maexvie** [comment]
Hi,

danke für die rasche Antwort. Es ist allerdings so, dass es aus den “Mitteilungen” auch - ungelesen - verschwindet. Und das war vor dem Update nicht so. D.h. wenn ich nicht innerhalb der wenige Sekunden das Popup bestätige, kann ich die Nachricht nicht mehr lesen.

Grüße,

Marcus

**Comment by hufman** [comment]
When you see a message notification come up and then go away, does it actually clear from your phone's notifications as well? The [autohide logic](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/PopupAutoCloser.kt) can only hide the popup window, it has no other interaction with the notification.
To clarify, are you viewing the correct Notifications screen? AAIdrive can add messages to the ID5+ car's notifications list, which is how it shows a statusbar icon for unread messages, and this message list is ephemeral. On the other hand, AAIdrive also provides a full Notifications list which always shows the current notifications from the phone, and is easy to tell apart by having a list of settings at the bottom. It looks [like this](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/res-facets/tips/drawable/pic_news_list_mini_id5.jpg). To get to this screen, you can click into the [unlabeled book icon](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/res-facets/tips/drawable/pic_news_entrybutton_mini_id4.jpg) in ConnectedDrive menu or the [Notifications book icon](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/res-facets/tips/drawable/pic_news_ambutton_bmw_id5.jpg) from the Office/Communication menu.

**Comment by Maexvie** [comment]
#response_container_BBPPID{font-family: initial;font-size: initial;color: initial;}  Hi Walter,Sorry for changing to German; your name sounded like. Well, I'm talking about e.g. SMS or Whatsapp, no BMW messages. So far a SMS poped up and stayed in the notification list until deleted. After update It only pops up and will no longer appear in message list. Send you pictures attached.br      Marcus                                                                                                                                                                           Von: ***@***.***: 27. Januar 2022 20:51An: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [BimmerGestalt/AAIdrive] New Release delete Messages (Issue #514)  
When you see a message notification come up and then go away, does it actually clear from your phone's notifications as well? The autohide logic can only hide the popup window, it has no other interaction with the notification.
To clarify, are you viewing the correct Notifications screen? AAIdrive can add messages to the ID5+ car's notifications list, which is how it shows a statusbar icon for unread messages, and this message list is ephemeral. On the other hand, AAIdrive also provides a full Notifications list which always shows the current notifications from the phone, and is easy to tell apart by having a list of settings at the bottom. It looks like this. To get to this screen, you can click into the unlabeled book icon in ConnectedDrive menu or the Notifications book icon from the Office/Communication menu.

**Comment by hufman** [comment]
Good afternoon! It seems that Github blocks picture attachments when replying via email, please attach them to the Github issue directly.

**Comment by Maexvie** [comment]
![IMG_20220128_1142396](https://user-images.githubusercontent.com/98543476/151797233-49fc2565-440b-4225-9136-ee22e0470446.jpg)
![IMG_20220128_1142191](https://user-images.githubusercontent.com/98543476/151797242-946a5796-8c6b-4163-bc38-7d393d648d86.jpg)
![IMG_20220128_1140169](https://user-images.githubusercontent.com/98543476/151797251-732aeec5-19ca-43a2-ac65-dfaaf1999123.jpg)

**Comment by hufman** [comment]
Ah yes, this is the car's own Notifications Center. AAIdrive's Notifications app [shows a settings panel](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/res-facets/tips/drawable/pic_news_list_mini_id5.jpg), and AAIdrive's window title (in German) says [Benachrichtigungen](https://github.com/BimmerGestalt/AAIdrive/blob/90026a3ca64b7d0538dab79c193efb0e999dbe8f/app/src/main/res/values-de/strings.xml#L344-L345) instead of Mitteilungen.

Notifications will show up in the car's Notification Center if they do not show in a popup, for example if you have disabled popups or if the popup is suppressed due to a passenger being detected. This behavior has been in place for a [long time](https://github.com/BimmerGestalt/AAIdrive/blame/main/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/PhoneNotifications.kt#L367), because using the car's Notification Center the only way to show the statusbar icon in ID5.

Look in the car's Online Services or Communications menu to find the [book icon](https://github.com/BimmerGestalt/AAIdrive/blob/96ad7734ba63c3900baf01f0503f1128507f99cc/app/src/main/res-facets/tips/drawable/pic_news_ambutton_bmw_id5.jpg) which will take you to AAIdrive's Notifications app.

**Comment by Maexvie** [comment]
Hi Walter,

you are right. As soon as there is a passengers phone detected no pop up will show up. I will now disable popup in the AAI app and check, what will happen. 

Thx so far

**Comment by hufman** [comment]
Were you able to find AAIdrive's notification list, the one with the Options list at the bottom?

**Comment by Maexvie** [comment]
Hi Walter,

I disabled pop up in the App and now it is working properly.

Thx,

Marcus
