### ISSUE TITLE
Improvement: Integrating Messenger

### ISSUE THREAD

**Issue by chschilling** [BimmerGestalt/AAIdrive#521]
Hey,

thanks for the great app first ;)

is there any way or plan to integrate messengers like whatsapp or threema?
Would be nice to write messages via Voice recognition without the need to always use sms :)

Greetings :+1:

**Comment by hufman** [comment]
Thank you for the kind words!
I don't know of a good way for an app like AAIdrive to integrate into messaging apps on the Android platform, such as loading user lists or sending new messages in the background as opposed to opening up the messaging app's own chat screen. If that were figured out, it would surely be possible to extend this functionality to a car interface. Until then, the only option is to reply to the messaging app's notification popup.
Android Auto itself supports messaging apps (and other apps) only because the apps have provided an Android Auto specific UI. It is a different integration model compared to the generic data and control method of the Android Auto music app integration, which AAIdrive is unable to use.

**Comment by unlive74** [comment]
By the way, when a voice call comes in, does the messenger give the name of the person who is calling through the Android Auto interface? Maybe it's possible to show this name on the iDrive display?

**Comment by samusishere** [comment]
Not sure if this would be of any assistance or not to the inquiry listed above, but I decided to use navituning's permanent r t t i solution. This "update" allows for users who were either affected by the 3G sunset, or who just refuse to pay BMWs excessive pricings for connected dry packages, to still utilize some connected car features without a subscription. With that on top of it, they've been abled data connection via Bluetooth, therefore it allows for your mobile device to communicate directly with the vehicle sending and receiving data, which after some experimentation I've noticed actually allows for the native voice recognition by dragon software that was introduced for replying to emails and text messages (not the voice memos) is able to properly function again without a connective drive subscription that is active. Now, with the understanding that this would obviously include some tinkering with iDrive and some additional coding that some people may not be comfortable with, and are not not willing to purchase navituning's option, I'm thinking that maybe there will be a possibility to trigger the dragon voice recognition speech to text software for feature such as this? Just a thought.

**Comment by hufman** [comment]
The car's incoming call screen pulls data directly over Bluetooth from the phone, and there isn't a way for AAIdrive to add extra data to this screen.
AAIdrive uses the car's input screen to reply to notifications, and if your car has speech recognition enabled, the input screen should have a speech transcription option in this input screen. I believe this is enabled by default for ID5, so if you figured out how to enable speech transcription for ID4, please feel free to document it in the Discussions tab!
