### ISSUE TITLE
Alexa ha dejado de funcionar

### ISSUE THREAD

**Issue by Toskilabis** [BimmerGestalt/AAIdrive#542]
Hola desde haces unos días Alexa ha dejado de funcionar con la opción Push and Talk en ID5. Ha funcionado perfectamente con Android y de un día para otro cuando presionas el comando de voz se oye un mensaje : " Esta opción no está disponible actualmente".
La suscripción Conected Drive esta activa, he vuelto a desinstalar e instalar las apps My BMW, AutoIdrive y Alexa vinculando mi cuenta Amazon de nuevo en My BMW y no consigo hacerlo funcionar mediante comando de voz 
Alguna opinión al respecto?
Gracias

**Comment by hufman** [comment]
It sounds like you are talking about BMW's native Alexa integration (found under the [Vehicle Apps menu](https://cdn.bmwblog.com/wp-content/uploads/2020/07/alexa-bmw.jpg)) as opposed to AAIdrive's shortcut icon (found under the [Smartphone Apps menu)](https://i.ytimg.com/vi/6umvOBYReYA/maxresdefault.jpg). Since AAIdrive doesn't have any control over the native Alexa integration, I'll close out this issue and let's continue in the discussion #544.
