### ISSUE TITLE
Search does only show start Page

### ISSUE THREAD

**Issue by X5Driver** [BimmerGestalt/AAIdrive#558]
Hi, first thank you for the work on the app

The browse  function does only show the start page of Spotify,  no longer the library (Playlist / Albums) 
Did not change anything. Before it was working.

Update 
I saw now there's already a solution,  when can we expect the release in the store?

**Comment by hufman** [comment]
This sounds like you are encountering the new behavior of Spotify 8.7, as discovered in #549. What version of AAIdrive are you running? This bug is fixed in version 1.3.2-85-4891cd2, and is available in the Play Store beta test builds and in the Github nightly build. The fix will be more widely available with the upcoming release of AAIdrive 1.4.

**Comment by X5Driver** [comment]
Thank you.
I had to update to 1.3.2-85-4891cd2 since i got the Spotify update to 8.7.16.1354

Looking forward to the 1.4 version. In the 1.3.2 the media button does not work like before, you will not go to your media sources, it will try to open (shows short and close again) but stays in Spotify.

Would like to see all the entry's from the "default" list in a separate folder like "start" because it is the start page and it looks better.

Start (startpage)
Browse (genres/ search)
Library (album / playlists) 

But I'm happy anyway that it is working again to find the library..

**Comment by hufman** [comment]
I believe the behavior you describe, of jumping right to Spotify instead of showing the main Media menu, is actually a recent bug fix (#500)! This more correctly matches the behavior of other Media sources, like the Radio or USB sources, where the Media button will directly open the currently-playing media source. Once inside the music playback screen, you are correct that the Media button opens up a little menu of other media sources, but due to protocol limitations it can only show the Spotify app in this menu. You must click the first toolbar button to bring up a list of phone music apps, or you can back out to the main Media menu to pick a different app.

The browse list comes directly from Spotify (with these Browse and Library items added manually). I prefer to keep this bigger list, because it provides quicker access for the driver to just play some music without needing to spend extra time clicking through menus while driving.

Thank you for the bug report, and I'm glad we got it figured it out!
