### ISSUE TITLE
New Android Auto app doesn't allow to start GMaps 

### ISSUE THREAD

**Issue by HaivanJV** [BimmerGestalt/AAIdrive#578]
The new version of Android Auto mobile app allows the execution of phone apps only from car screens. (see screenshot).
The side effect is that now GMaps cannot be launched within Android Auto and, consequently, when in screen mirroring it has the same FPS cap as any other screen casting.
This is the same also when AAIdrive is in USB mode.

Is there any possibility to lift the FPS cap for GMaps only? Can AAIdrive detect which app is opened from the background?

Thanks for all the hard work!
<img width="327" alt="image" src="https://user-images.githubusercontent.com/22883596/170426660-28b59bbe-0087-4aa4-a66c-2ad443579d1e.png">

**Comment by hufman** [comment]
Good morning! That is disappointing to hear!
Android doesn't provide a good way to tell what app is in the foreground :( The Android Auto detection [checks a global Car UI Mode flag](https://github.com/BimmerGestalt/IDriveConnectAddons/blob/1034898d866f55369c0747b646c36ece6f23a497/screen_mirror/src/main/java/io/bimmergestalt/idriveconnectaddons/screenmirror/carapp/CarApp.kt#L193), and doesn't provide any further options.
I did update Screen Mirroring to go at 1fps instead of 0.5fps while in motion a few months ago, are you using that version?

**Comment by HaivanJV** [comment]
I'm using 1.3.2-114-52ea6bd-bmww_xl
I am not sure when I last got this nightly build

**Comment by hufman** [comment]
Screen Mirroring is a [separate app](https://github.com/BimmerGestalt/IDriveConnectAddons/releases/tag/latest_build) with its own versions. I believe it will still include the git hash in there, to help you figure out what code version you have installed.

**Comment by HaivanJV** [comment]
I wasn't able to fetch the file I downloaded with the version. I will try to install the most recent version and re-test

**Comment by HaivanJV** [comment]
Tested the latest version in USB mode. It can only work smoothly when the car is stationary. When in movement, the FPS cap is lowering sensibly the quality of the experience, which was not the case before when Maps was running under Android Auto. I guess there is not much else we can do here...

**Comment by hufman** [comment]
Unfortunately there isn't any good way to detect the running Maps app :(
