### ISSUE TITLE
UI sometimes "crashes"

### ISSUE THREAD

**Issue by Vasmares** [BimmerGestalt/AAIdrive#591]
Hi,

90% of the time the connection and all the features work fine.
Sometimes I have the issue, that the In-Car UI "crashes"

![photo_2022-06-25_17-26-19](https://user-images.githubusercontent.com/10863304/175780187-57263504-d781-491e-b5ec-d7309906e9dc.jpg)

The current title is not displayed anymore.
I cant select tracks via the onscreen or steering wheel.
The tracktime is not correct, 
The album cover art does not display...

It seems to happen when I am "too fast" in selecting and changing tracks.
In my case I do it via my HUD and the steering wheel buttons.
Or when selecting another album via the in-car UI.

It only helps to disconnect bluetooth / the phone and close the used apps on the phone.
Then wait ~5 min and then reconnect the phone.
Then everthing works fine again.

Build: 1.4.03.05.2022

Did you get what I am on about ?

**Comment by bogdan-calapod** [comment]
I've also experienced this and it usually happens when the phone runs out of memory - not sure AAIdrive can do anything about that 🤔

**Comment by Vasmares** [comment]
I also thought of that, but the RAM was fine. I am running on as Samsung Galaxy S22 Ultra. That one has 12GB of RAM
The usage was by about 9GB. 
Is there a way of "checking" if the connection died / timeouted within the AAIdrive App ?

**Comment by bogdan-calapod** [comment]
I've also experienced similar issues on an S21 with RAM+ enabled. 

Did you make sure to disable battery optimizations for AAIDrive and MyBMW, as well as disable adaptive battery ? I've seen improvements after doing this.

> Is there a way of "checking" if the connection died / timeouted within the AAIdrive App ?

Apart from checking the `logcat` for any errors, I don't think so.

**Comment by hufman** [comment]
The connection from AAIdrive to the car is easy to test: Pushing the Media button or selecting any of the apps in the Media menu, or clicking the Notification app, or clicking any of the toolbar buttons within the app, will make the car request the next menu destination from AAIdrive while handling the button click. If AAIdrive connection to the car is stuck, then this button press will appear to not respond.
The connection from AAIdrive to Spotify is harder to test, and I could imagine would look like the symptoms you see. You can try switching to a different music app within AAIdrive, and then switch back to Spotify, to reconnect this connection. To isolate it further, you can try playing around with the mini-player in the AAIdrive phone interface, to see if you can replicate the crash there. If it is a problem in the Spotify connection, that is harder to fix, because it's handled entirely through the Spotify SDK.

**Comment by Vasmares** [comment]
This seems to be fixed.
The I am on v1.4.1 nightly build of 10th Feb 2023, and everything is very stable and fast.

No matter how hard I tried to get the UI to crash, it just works :D 

Very nice
