### ISSUE TITLE
Podcast Addict only plays one podcast, no interactions function

### ISSUE THREAD

**Issue by idesignstuff** [BimmerGestalt/AAIdrive#600]
It only plays a podcast. It won't allow FF or rewind, either with left/right arrow buttons under center display or by steering wheel up/down media buttons. When it's interrupted by any other message, it stops and won't start again, even with the media power button cycling.

**Comment by hufman** [comment]
It's hard to debug this, since the Podcast Addict app is responsible for offering or handling the commands such as skipping tracks. It doesn't even provide a seek command for Android Auto like PocketCasts does, which AAIdrive includes support for (#350).
It looks like playing a single episode is the default behavior in Podcast Addict itself, with a separate Add To Playlist button to queue up multiple episodes, and such extra buttons are not generically available over the Android MediaController API.
It's weird that an interruption causes Podcast Addict to stop, but that shouldn't be AAIdrive specific. The Power Off/On button triggers the car to ask the app to go back to its previous playback state, which won't help if it was already paused. Try selecting Podcast Addict again from the main Media menu to start playback.

**Comment by idesignstuff** [comment]
Walter, first of all, thank you for the massive effort to build this
amazing app! It's been a fantastic addition to my new Mini. Being able to
send destinations from plugshare or ABRP is priceless.

The podcast app I use has been less great, but that's clearly not because
of you. I did find that there are actions in the podcast addict player, but
they are like 4 clicks to get to using either touch or iDrive interfaces.

I also can't assign those actions individually to the 6 preset buttons
below the display. Is this all podcast addict's choices?

I'll try out the other podcast app to see how it is integrated.

Thanks again!

Christian

**Comment by hufman** [comment]
Unfortunately, the car protocol doesn't allow me to easily allow Actions to be added to the preset buttons.
Hopefully other podcast apps work better for you! The main project [README](https://github.com/BimmerGestalt/AAIdrive#implemented-features) lists a few other podcast apps that are able to be launched by AAIdrive and should work well.

**Comment by idesignstuff** [comment]
I have switched to pocket casts and it works much better with the mini
using aaidrive. Great work! Thank you.



Christian

**Comment by hufman** [comment]
Glad to hear it!
