### ISSUE TITLE
Spotify 

### ISSUE THREAD

**Issue by minisydney** [BimmerGestalt/AAIdrive#609]
I have a late 2021 Mini with the most recent version of iDrive. I've followed all instructions, but for some reason although all my apps appear as expected, more often than not Spotify refuses to be controlled via the car dash and when I click on the Spotify logo nothing happens. I get the cover art and can skip tracks using the steering wheel controls, but I cannot do anything else on the car. On occasion the full Spotify menu pops up and I can search playlists etc... but soon this defaults back to what I described above. I have tried everything but can't get this to work properly. Any suggestions?

**Comment by minisydney** [comment]
Thanks, I did try to mark all apps as having free reign to use as much battery as they need, but I might try turning off my overall Power Saving setting and see if that works!

**Comment by minisydney** [comment]
I tried last night with all power saving settings off and unfortunately the same issue. It seems that within a couple of minutes all controls on the car seize up, apart from the ability to switch tracks.

**Comment by rsyring** [comment]
Have you tried changing your AVRCP version?  https://www.reddit.com/r/BMWi3/comments/u4i3pf/pixel_6_pairing_issues/

**Comment by Vasmares** [comment]
Hey, I had the same issue.
Sometimes the UI of my ID5 just froze. Although it was still showing the spotify icon in MINI Connected, I could not access it.
I had to change to bluetooth audio to change tracks and stuff.

My solution: Update

On a recent basis, I install the nightly builds of this app.
since v. 1.4 i guess, this is completely gone.

Everything is very stable and fast.
I tried to get it to crash to file a bug report, but it  just wouldnt...
Maybe that helps you too ?

Nightly build : (Apk)
https://bimmergestalt.s3.amazonaws.com/aaidrive/builds/androidautoidrive-latest-main-nomap-sentry-release.apk

**Comment by hufman** [comment]
AVRCP version shouldn't matter, the apps talk directly over the Bluetooth Serial Port Profile.
You could try uninstalling and reinstalling MyBMW and AAIdrive to clear the phone's cache, which seems to temporarily keep the phone from killing it in the background. Definitely make sure that all battery optimization options are checked, because some phone brands add extra options and aggressively kill things.

**Comment by rsyring** [comment]
> AVRCP version shouldn't matter, the apps talk directly over the Bluetooth Serial Port Profile.

I trust you know a lot more about this than I do.  But, I can guarantee you that it matters in some cases.  When I run with the default version the audio/connection locks up regularly.  When I change, it almost never does.  I'm a software developer and I spent days troubleshooting this.  That's the only thing that made a difference.

FWIW, the lockup is often related to the transition of audio from one format to another.  It was especially prevalent when I would receive a phone call and then hang up.  In that case, there was a high probability that the connection would lock up.    It would also happen when switching tracks.

Also, in my case, this isn't just a spotify doesn't play thing.  The entire connection is whacked.  I can't get iDrive to even disconnect the phone.  The BT connection becomes completely unresponsive.  Even if I disconnect the phone from BT manually, iDrive still shows it as connected.  Furthermore, in my 2015 X5M, this issue destablizes iDrive so much that sometimes it affects other types of media (playing from the integrated hard drive) and will cause iDrive to completely reboot itself.  

When this lockups happen, the ONLY thing that gets them to recover in the moment is rebooting iDrive and also rebooting the phone.  It also fixes itself if I leave the car for some time (groceries/restaurant), which reboots iDrive, and then come back.  In that case, I don't need to reboot the phone.

This may not be an AAIDrive thing or related to this issue but what I've described above is definitely a problem and I've found numerous reddit and forum reports out there with similar issues.  Just wanted to leave this info here in case someone else comes across, has the same issues, and wants to confirm they aren't alone.  :)
