### ISSUE TITLE
Android media player Emby starts file from the beginning

### ISSUE THREAD

**Issue by mastervol** [BimmerGestalt/AAIdrive#618]
I have a strange issue to report but this has happened often now.

If I use the Android Emby player from https://emby.media/ without the car connection I can click on pause.
Then let AAIdrive connect, then choose the Emby player icon in the BMW console and the player picks up where I paused.

There have been occasions where I did not use the player before or the player has been closed on Android.
Then the car connects to AAIdrive and I click on Emby and the player starts the file from the beginning, which is obviously not what I want. It should never start or initialise from the beginning, unless I have not played a file before.

Is there anything on AAIdrive's end to improve this?

Thanks

**Comment by hufman** [comment]
Hmmm there's not much AAIdrive can do about this, it's only calling `.play()` when it first connects.
What happens when you kill Emby and then open Emby from the AAIdrive phoneui Music tab and press Play in the miniplayer? This should replicate what the car is doing.
Unfortunately, I can't easily check what Emby is doing differently with a Bluetooth connection or the Android API connection. Do you have a car (or a friend with a car) with Android Auto available to test behavior?
