### ISSUE TITLE
Detail car info menu item

### ISSUE THREAD

**Issue by markoreg** [BimmerGestalt/AAIdrive#680]
Hi. First, the new feature is great. May i suggest to maybe expand the options and to make it configurable in the app, for user to choose limited numer of items to be displayed on the idrive screen.
I wanted to report the issue with menu item that has no text and image. It is just blank item, so can be open only by guessing.
Items on the detail car info screen are clickable, bit when it opens the item it is only the blak screen. I guess that items should not be selectable or clickable.
Another issue that happened when i installed the new version was that car kept making the self call (my phone number was displayed on the idrive). It happened few times during the jurney, and again on the way back to home. It stopped when i opened the app and didnt happened again.

**Comment by bogdan-calapod** [comment]
> I wanted to report the issue with menu item that has no text and image. It is just blank item, so can be open only by guessing.
Items on the detail car info screen are clickable, bit when it opens the item it is only the blak screen. I guess that items should not be selectable or clickable.

Hey - AFAIK this is a limitation of the BMW API, so not sure there can be anything done for this.

**Comment by hufman** [comment]
Thank you for the compliments!
As an unofficial project, AAIdrive is limited in the design of the applications. The particular car app that is used by the new Car Info screen is technically the old BMW Classic RSS News app, which was previously used by AAIdrive to gain access to the car's Text To Speech system. Since that app must take up space in the menu anyways, a user provided a proof of concept implementation in #653 of using that (otherwise empty) app to show some car data.

The entry in the menu is hardcoded to use a specific icon and label, and in this case it would show the BMW Classic icon and say "News", except that AAIdrive suppresses those labels and all of the other hardcoded text within the app. It could be possible to show the icon, since no other car app currently shows the Connected Classic icon. The app layout is also hardcoded, and so the data is clickable and navigates to a blank screen, and AAIdrive is unable to change this behavior.

The one thing that AAIdrive is able to do is add custom icons elsewhere, and so this new Car Info app adds itself to the Vehicle Information screen.
![photo1678462104](https://user-images.githubusercontent.com/1592375/224359698-d66ea6b2-ac76-4885-850f-f8eab8953960.jpeg)

AAIdrive does not make any calls, perhaps you were receiving an app call (such as Google Voice, Telegram, or WhatsApp) which would show such a phone number. Development on AAIdrive has slowed down a lot since it became feature-complete last year, so there [haven't been any changes](https://github.com/BimmerGestalt/AAIdrive/compare/1.4.1...main) that would trigger any phone calls.
