### ISSUE TITLE
where can i find some docs about add homebrew app into idrive

### ISSUE THREAD

**Issue by galenzhao** [BimmerGestalt/AAIdrive#696]
Hi,

I'm new to aaidrive.
The app works well on my bmw.
 
And I found a new section added to idrive .
![image](https://user-images.githubusercontent.com/3184101/236624491-1728fc3f-e29d-443f-b154-a9a6a0e9194f.jpeg)
![image](https://user-images.githubusercontent.com/3184101/236624501-497fe48f-b4e5-4c72-92ff-fe2a395d17fb.jpeg)
![image](https://user-images.githubusercontent.com/3184101/236624515-00831ce5-7cb7-49b2-a489-c297aabd21d6.jpeg)

There is a ‘detail vehicle info’ menu added to ‘my bmw’. With some engine info.
It seems like the menu is not an idrive hidden function. But implemented by aaidrive.

Could you tell me where can I get some docs that can help me to implement a new menu and show some text on it?

Or just point out where the ‘detail vehicle info’ menu is implemented in aaidrive?

Thanks.

**Comment by hufman** [comment]
This feature is the Advanced Vehicle Information app (discussed in #653). It lives within the [ReadoutApp](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/ReadoutApp.kt), which needs to add a blank icon in the ConnectedApps menu to enable TTS support for Notifications, and so this secondary use was found for it ([source for the views](https://github.com/BimmerGestalt/AAIdrive/tree/main/app/src/main/java/me/hufman/androidautoidrive/carapp/carinfo/views). Then, an AM app icon was added to the Vehicle Info menu as a shortcut to get to it.

The ability to create new applications is hindered by the car's signature requirements: Any apps that add car UI must have those resources signed by BMW, including the menu layout and any icons and text packs. Because of this limited flexibility, I have not prioritized documenting how to create new apps.
There are several examples to modify, if you wanted to experiment! Besides the various AAIdrive modules, the [screen mirroring](https://github.com/BimmerGestalt/IDriveConnectAddons/tree/main/screen_mirror) and [Home Assistant](https://github.com/BimmerGestalt/HassGestalt) addons demonstrate a native UI.

What would you like to add to the car?

**Comment by galenzhao** [comment]
> This feature is the Advanced Vehicle Information app (discussed in #653). It lives within the [ReadoutApp](https://github.com/BimmerGestalt/AAIdrive/blob/main/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/ReadoutApp.kt), which needs to add a blank icon in the ConnectedApps menu to enable TTS support for Notifications, and so this secondary use was found for it ([source for the views](https://github.com/BimmerGestalt/AAIdrive/tree/main/app/src/main/java/me/hufman/androidautoidrive/carapp/carinfo/views). Then, an AM app icon was added to the Vehicle Info menu as a shortcut to get to it.
> 
> The ability to create new applications is hindered by the car's signature requirements: Any apps that add car UI must have those resources signed by BMW, including the menu layout and any icons and text packs. Because of this limited flexibility, I have not prioritized documenting how to create new apps. There are several examples to modify, if you wanted to experiment! Besides the various AAIdrive modules, the [screen mirroring](https://github.com/BimmerGestalt/IDriveConnectAddons/tree/main/screen_mirror) and [Home Assistant](https://github.com/BimmerGestalt/HassGestalt) addons demonstrate a native UI.
> 
> What would you like to add to the car?

ok, isee.

thanks for the info.
