### ISSUE TITLE
MyTriumph app interferes

### ISSUE THREAD

**Issue by JPersson77** [BimmerGestalt/AAIdrive#713]
Hi, 

The other day I had trouble with aaidrive (the apps connection was not functioning so no spotify integration). After a long time of trying to troubleshoot I noticed that the mytriumph app was trying to connect to the bmw (or atleast the mytriumph notification said so). It should not do that, as it's an app for the connected head unit of my triumph motorcycle. Uninstalling mytriumph resolves and reinstalling it brings the issue back.

Not sure why this is happening, but I just want to leave the info here in case it might benefit someone

**Comment by hufman** [comment]
Fascinating! I bet it's because both MyBMW and MyTriumph see that the car has the SPP option and they both try to connect.
I saw that the MyTriumph app does check that the name starts with TRI, but I can't tell how it would skip that check and try to connect anyways. You should report this bug to the Triumph developers.

Instead of uninstalling and losing authentication and garage information, you could revoke the Local Devices permission from MyTriumph, which should prevent it from trying to connect and be fast enough to grant when you want to ride your motorcycle.

**Comment by JPersson77** [comment]
Thanks! There are loads of issues with the mytriumph app so it's not surprising, but I will take your info here and make a bug report to triumph

Thanks for the pointers on revoking local devices permission, I have force stopped it so far but this seems like an easier way :)

**Comment by hufman** [comment]
Did you hear back from them yet? I'm very curious :)
