### ISSUE TITLE
FlitsMeister

### ISSUE THREAD

**Issue by GlennV90** [BimmerGestalt/AAIdrive#716]
Hi,
Would it be possible to use FlitsMeister on the screen without screen mirroring?

I don't like the screen mirror as it requires the phone to be on at all times. For GPS etc the delay is annoying in my opinion.
If there's a solution for that, i would like to hear it as well :)

thanks!

**Comment by hufman** [comment]
Good afternoon!
Looking at the FlitsMeister website, it doesn't look like they offer any API or SDK to embed their app within another app. The map module of AAIdrive embeds the Google or Mapbox SDK into a background window so that it can screenshot it while the screen is off, which is the only way I found how to do it. I haven't found any way to screenshot the entire phone screen while the screen is off either. However, this part is just standard Android hackery, so any other Android developer could contribute workarounds for this if it's possible!
