### ISSUE TITLE
Detailed Vehicle Information Always Opens When Selecting Spotify

### ISSUE THREAD

**Issue by LACNR** [BimmerGestalt/AAIdrive#723]
Good Morning, 
 
I've got a little something with the latest public 1.4.2 Release, first of nicely Integration of the Detailed Vehicle Information, though I noticed a Problem if you will. When for example, selecting Spotify in the Multimedia Screen it always jumps into the Detailed Vehicle Information screen instead which can be any of them depending which Car Information you lastly selected at use - to return or go to Spotify you have to click the Back Button of your Controller and eventually select Audioplayer instead of it doesn't go to Spotify right away. 

Anyone else noticed this repeating phenomenon? 

Though I noticed, you can now directly select Audioplayer and it opens Spotify instead of selecting the App first and then Audioplayer (ID4++) or vice versa.

**Comment by hufman** [comment]
I think ID4 has some quirks about the way AAIdrive opens app screens from certain shortcut icons. The various music app icons are shortcuts that set the active app and then try to switch to the Audioplayer app, and I noticed sometimes they would fail to open Audioplayer before I lost access to an ID4 car several years ago.
However, my ID5 car doesn't seem to have these issues, so I've since added more shortcut icons: The Phone Notifications icon in the office section is a shortcut to the book icon in the ConnectedDrive menu, and now the new Car Information icon is a shortcut to one of the other label-less icons.
I apologize for ID4 not working perfectly, I don't know how it can be fixed. You can reliably use the actual app icons in the ConnectedDrive menu, which will work perfectly.
