### ISSUE TITLE
AAIdrive not connecting to car properly

### ISSUE THREAD

**Issue by Juschtus** [BimmerGestalt/AAIdrive#823]
I have a 2013 BMW F34 GT with NBT and can't seem to connect to my car. Only the first Setup works, after I disconnect the USB cable, the App Just keeps cycling between connected and not connected. I use Connected Drive Version 6.4.1. 

I got every feature working, but only after the Initial Setup. (Clean Reinstall of both Apps, AAidrive and connected Drive)

**Comment by hufman** [comment]
The app showing as connecting and disconnecting repeatedly is a symptom I've seen when MyBMW is struggling to keep connected over USB. I haven't seen similar behavior on BMW Connected. Reinstalling AAIdrive should not impact the car connection, only the official app is responsible for the actual car connection. Make sure you only have one version of the official car app installed. Instead of uninstalling and reinstalling, try force-closing and re-opening.
Unfortunately, the car connection itself is not controlled by AAIdrive, so I can't offer any solid fixes.

**Comment by Juschtus** [comment]
Alright, I fixed it by plugging in the USB cable before starting the Idrive System. Now, the only problem is, that after about half an hour, the entire system glitches out. Missing Text, Red flashes and White Stripes all over the Screen. The connection stays stable, I just can't really use my System at all and have to completely restart it to fix everything.
